In [39]:
import numpy as np

In [40]:
print(np.array(range(0,100, 2)))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [41]:
a1=np.arange(0,100,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [42]:
#linspace --> it is used to divide the numbers into equal parts. It also includes the stop value. If we don't to include the stop value, we can use endpoint=False.


# linspace(start, stop, num, endpoint=True, retstep=False)
# start --> strat value
# stop --> end value
# num --> number of samples to generate. Default is 50
# endpoint --> if True, stop is the last sample. Otherwise, it is not included. Default is True
# retstep --> if True, return (samples, step). Default is False

np.linspace(0,10) 


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [43]:
''' zeros function  '''

np.zeros(2)   # zeros --> It is used to create the matrix which contains only zeros. syntax --> zeros(numbers) , numbers --> size of the matrix

array([0., 0.])

In [44]:
np.zeros((2,3))   # here 2 --> rows  and 3 --> columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros((2,3,4))  # here 2 --> means number of blocks, 3 --> nnumber of rows and 4 --> number of columns

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [46]:
''' ones() function 
It is used to create the matrix with only 1
'''
np.ones(2)

array([1., 1.])

In [47]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
''' eye() function
it is used to generate the diagonal (identical) matrix. It generates the square matrix always

'''
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.eye(4)   #It is not mandate to pass the 'm' value but 'n' is mandate

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
''' 
full() function

It is used to create the matrix with given value only

'''

np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [52]:
import numpy.random as rd

rd.randint(10)        # randint --> it is used to generate the random integer numbers

0

In [53]:
rd.randint(10,100)  # it is used to generate the random integer number between 10 to 100

40

In [54]:
rd.randint(10,100,(3)) # It is used to create the random number in form of matrix

array([90, 17, 86], dtype=int32)

In [55]:
rd.randint(10,100,(3,2)) # It is used to create the random number in form of matrix and here 3 indicates the number of rows and 2 indicates number of columns


array([[25, 63],
       [90, 37],
       [54, 87]], dtype=int32)

In [ ]:

rd.seed(5)  # It is used to fix the number
rd.randint(10,100,(3,2))

array([[88, 71],
       [26, 83],
       [18, 72]], dtype=int32)

In [ ]:
rd.rand() # It is used to genearte the folating point number between 0 & 1 and that number must be positive number

0.7659078564803156

In [58]:
rd.rand(3)

array([0.51841799, 0.2968005 , 0.18772123])

In [59]:
rd.rand(2,3)

array([[0.08074127, 0.7384403 , 0.44130922],
       [0.15830987, 0.87993703, 0.27408646]])

In [65]:
''' randn() method 
It is same is rand() but randn() generates the negative numbers also and it is in the range between -1 & 1
Its mean is near to zero (means it is in negative form) and standard deviation is near to one (means it is in positive form)
'''

r=rd.randn(2)
print(r)

print(np.mean(r))
print(np.std(r))

[0.99643983 0.71242127]
0.8544305488949648
0.14200927801839708


In [70]:
'''
choice() ---> It is used to select one or more values from given list.
'''

l=[10,34,56,87,43,568,9,0]
r1=rd.choice(l,2)  # It is used to select the given number of random values from above list
rd.choice(l,(2,3))

array([[ 34, 568,   0],
       [ 10,   9,   9]])

In [98]:
colors=['black', 'brown', 'red', 'green', 'yellow', 'pink', 'white', 'purple', 'maroon', 'blue']

rd.choice(colors,4, replace=False, p=[0.2, 0.04, 0.02, 0.25, 0.04, 0.03, 0.12, 0.13, 0.023, 0.147]) # if we give replace=False then we won't get any repeated values.

array(['blue', 'purple', 'black', 'green'], dtype='<U6')