In [1]:
import numpy as np

In [2]:
print(np.array(range(0,100, 2)))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [3]:
a1=np.arange(0,100,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [4]:
#linspace --> it is used to divide the numbers into equal parts. It also includes the stop value. If we don't to include the stop value, we can use endpoint=False.


# linspace(start, stop, num, endpoint=True, retstep=False)
# start --> strat value
# stop --> end value
# num --> number of samples to generate. Default is 50
# endpoint --> if True, stop is the last sample. Otherwise, it is not included. Default is True
# retstep --> if True, return (samples, step). Default is False

np.linspace(0,10) 


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [5]:
''' zeros function  '''

np.zeros(2)   # zeros --> It is used to create the matrix which contains only zeros. syntax --> zeros(numbers) , numbers --> size of the matrix

array([0., 0.])

In [6]:
np.zeros((2,3))   # here 2 --> rows  and 3 --> columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((2,3,4))  # here 2 --> means number of blocks, 3 --> nnumber of rows and 4 --> number of columns

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
''' ones() function 
It is used to create the matrix with only 1
'''
np.ones(2)

array([1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
''' eye() function
it is used to generate the diagonal (identical) matrix. It generates the square matrix always

'''
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.eye(4)   #It is not mandate to pass the 'm' value but 'n' is mandate

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
''' 
full() function

It is used to create the matrix with given value only

'''

np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [14]:
import numpy.random as rd

rd.randint(10)        # randint --> it is used to generate the random integer numbers

1

In [15]:
rd.randint(10,100)  # it is used to generate the random integer number between 10 to 100

45

In [16]:
rd.randint(10,100,(3)) # It is used to create the random number in form of matrix

array([52, 78, 14], dtype=int32)

In [17]:
rd.randint(10,100,(3,2)) # It is used to create the random number in form of matrix and here 3 indicates the number of rows and 2 indicates number of columns


array([[49, 20],
       [13, 98],
       [70, 48]], dtype=int32)

In [18]:

rd.seed(5)  # It is used to fix the number
rd.randint(10,100,(3,2))

array([[88, 71],
       [26, 83],
       [18, 72]], dtype=int32)

In [19]:
rd.rand() # It is used to genearte the folating point number between 0 & 1 and that number must be positive number

0.7659078564803156

In [20]:
rd.rand(3)

array([0.51841799, 0.2968005 , 0.18772123])

In [21]:
rd.rand(2,3)

array([[0.08074127, 0.7384403 , 0.44130922],
       [0.15830987, 0.87993703, 0.27408646]])

In [22]:
''' randn() method 
It is same is rand() but randn() generates the negative numbers also and it is in the range between -1 & 1
Its mean is near to zero (means it is in negative form) and standard deviation is near to one (means it is in positive form)
'''

r=rd.randn(2)
print(r)

print(np.mean(r))
print(np.std(r))

[-1.66478853 -0.70017904]
-1.1824837835808228
0.4823047458908715


In [23]:
'''
choice() ---> It is used to select one or more values from given list.
'''

l=[10,34,56,87,43,568,9,0]
r1=rd.choice(l,2)  # It is used to select the given number of random values from above list
rd.choice(l,(2,3))

array([[34, 34,  9],
       [34, 56,  0]])

In [24]:
colors=['black', 'brown', 'red', 'green', 'yellow', 'pink', 'white', 'purple', 'maroon', 'blue']

rd.choice(colors,4, replace=False, p=[0.2, 0.04, 0.02, 0.25, 0.04, 0.03, 0.12, 0.13, 0.023, 0.147]) # if we give replace=False then we won't get any repeated values.

array(['green', 'red', 'black', 'pink'], dtype='<U6')

## Indexing:



In [25]:
lst=[1,2,3,4,5,6]
lst[0]

1

In [26]:
# lst1=[[1,2,33,4],[5,6,7,8],[9,10,11]] 
# If we try toconvert this into array it will give ValueError becuase each sublist must behave same size

lst1=[[1,2,33,4],[5,6,7,8],[9,10,11,12]] 

lst1[0][1]

# lst1[2,3]  TypeError: list indices must be integers or slices, not tuple


2

In [27]:
# To convert given list into array we use 'array' function

arr1=np.array(lst)

In [28]:
arr2=np.array(lst1)

In [29]:
arr1

array([1, 2, 3, 4, 5, 6])

In [30]:
arr2

array([[ 1,  2, 33,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2[1][2] # array can accept the multi-index

np.int64(7)

In [32]:
# Array also support slicing

arr1[::-1]
arr2[::-1] # It just reverse the outer elements but not inner elements.

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2, 33,  4]])

In [33]:
arr2[::][2] # It is sed to get that number of row

array([ 9, 10, 11, 12])

In [34]:
arr2[::, ::-1] # It just reverse the inner elements

array([[ 4, 33,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [35]:
arr2[::, 2] # It is used to get that number of column 

array([33,  7, 11])

In [36]:
arr2[::-1, ::-1] # it reverse all the elements including inner and outer elements.

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4, 33,  2,  1]])

In [37]:
arr2

array([[ 1,  2, 33,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr2[::2, ::2]

array([[ 1, 33],
       [ 9, 11]])

In [39]:
arr2[:1:, ::2]

array([[ 1, 33]])

In [40]:
lst2=[[[10,20],[30,40]],[[1,2],[3,4]],[[9,8],[7,6]]]
lst2

[[[10, 20], [30, 40]], [[1, 2], [3, 4]], [[9, 8], [7, 6]]]

In [41]:
arr3=np.array(lst2)

In [42]:
arr3[::-1]

array([[[ 9,  8],
        [ 7,  6]],

       [[ 1,  2],
        [ 3,  4]],

       [[10, 20],
        [30, 40]]])

In [43]:
arr3[::-1, ::-1]

array([[[ 7,  6],
        [ 9,  8]],

       [[ 3,  4],
        [ 1,  2]],

       [[30, 40],
        [10, 20]]])

In [44]:
arr3[::-1, ::-1, ::-1]

array([[[ 6,  7],
        [ 8,  9]],

       [[ 4,  3],
        [ 2,  1]],

       [[40, 30],
        [20, 10]]])

In [45]:
arr3[::-1, :1:, ::2]

array([[[ 9]],

       [[ 1]],

       [[10]]])