In [1]:
import pandas as pd
import numpy as np

In [2]:
l1=[1,2,3]
l2=[6,7,8]

In [3]:
arr1=np.array(l1)
arr2=np.array(l2)

In [4]:
type(arr2)

numpy.ndarray

In [5]:
type(arr1)

numpy.ndarray

## Operators

#### 1. Arithematic Operations

In [6]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1**arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)

[ 7  9 11]
[-5 -5 -5]
[ 6 14 24]
[   1  128 6561]
[0.16666667 0.28571429 0.375     ]
[0 0 0]
[1 2 3]


#### 2. Comparision or Relational Operator

In [7]:
arr1>arr2

array([False, False, False])

In [8]:
arr1<arr2

array([ True,  True,  True])

In [9]:
arr1==arr2

array([False, False, False])

In [10]:
arr1<=arr2

array([ True,  True,  True])

In [11]:
arr1>=arr2

array([False, False, False])

In [12]:
arr1!=arr2

array([ True,  True,  True])

#### any() and all()

#### all() --> it gives True if all conditons are True otherwise False

#### any() --> it gives True if any of one conditionis True otherwise False

In [15]:
print((arr1<5).all() and (arr2>5).all())

True


In [16]:
print((arr1<5).all() or (arr2>5).all())

True


In [17]:
print((arr1>5).any() or (arr2<5).any())

False


In [18]:
print((arr1<5).any() and (arr2>5).any())

True
