In [1]:
import pandas as pd
import numpy as np

In [2]:
l1=[10,20,30]
l2=[50,60,70]

In [3]:
a1=np.array(l1)
a2=np.array(l2)

### Broadcasting of an Array

#### It is nothing but applying a particular value to each and every element to arrray


### Rules:

#### Elements==Elements
#### Element == 1
#### Element == empty

In [4]:
a3=np.array([100,200,300,400])

In [5]:
# a1+a3

In [6]:
a4=np.array([[1,2,3],[4,5,6]])
print(a4.shape)

(2, 3)


In [7]:
a1+a4

array([[11, 22, 33],
       [14, 25, 36]])

In [11]:
a5=np.array([[[2],[3]],[[4],[5]],[[45],[56]]])
print(a4.shape)
print(a5.shape)
print()
print(a4+a5)

(2, 3)
(3, 2, 1)

[[[ 3  4  5]
  [ 7  8  9]]

 [[ 5  6  7]
  [ 9 10 11]]

 [[46 47 48]
  [60 61 62]]]
