In [12]:
import numpy as np

In [13]:
a1=np.arange(10,96,5)
print(a1)
print(a1.shape)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)


### Reshape Functions

#### It is going to convert one shape of array into another.
#### If we want to reshape the array then we have to check with multiple of that shape.

In [15]:
np.reshape(a1, shape=(6,3))

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80],
       [85, 90, 95]])

In [17]:
np.reshape(a1,(3,3,2))

array([[[10, 15],
        [20, 25],
        [30, 35]],

       [[40, 45],
        [50, 55],
        [60, 65]],

       [[70, 75],
        [80, 85],
        [90, 95]]])

In [19]:
a2=np.reshape(a1,(2,3,3))
print(a2)

[[[10 15 20]
  [25 30 35]
  [40 45 50]]

 [[55 60 65]
  [70 75 80]
  [85 90 95]]]


-1 is used to convert any type of array into 1-D array

In [20]:
np.reshape(a2,(-1))

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
a3=np.array([[10,20,30,40,50,78],[2,4,5,60,64,28],[11,9,37,92,55,68]])
print(a3)
print(a3.shape)
print(a3.ndim)       # It is used to check the dimension of the array

[[10 20 30 40 50 78]
 [ 2  4  5 60 64 28]
 [11  9 37 92 55 68]]
(3, 6)
2


In [29]:
np.reshape(a3, (3,2,1,3))
np.reshape(a3,(6,3))

array([[10, 20, 30],
       [40, 50, 78],
       [ 2,  4,  5],
       [60, 64, 28],
       [11,  9, 37],
       [92, 55, 68]])