In [1]:
import numpy as np

In [2]:
a1=np.array([10,20,30])
print(a1)

[10 20 30]


In [3]:
np.power(a1,2) #It is used to get the power of each element in array

array([100, 400, 900])

In [4]:
np.sum(a1) # It is going to add all the elements in the array

np.int64(60)

In [5]:
np.std(a1) # It is used to get standard deviation of particular arrray

np.float64(8.16496580927726)

In [6]:
np.mean(a1) # It is used to get mean of that particular array

np.float64(20.0)

In [ ]:
np.var(a1) # It is used to get the varience of that particular array. Varience checks how far our value is away from the mean value.

np.float64(66.66666666666667)

In [ ]:
a2=np.array([1,0,2]) # It is used to get exponential value for each element in the array
np.exp(a2)

array([2.71828183, 1.        , 7.3890561 ])

In [ ]:
a3=np.array([2.71828183, 1.        , 7.3890561 ])
np.log(a3) # It is used to retrieve the value of that power.

array([1., 0., 2.])

In [14]:
arr1=np.array([10,2,15,5,9,20])
arr1

array([10,  2, 15,  5,  9, 20])

In [ ]:
np.isin(20, arr1) # It works as membership operator
np.isin(2,arr1)

array(True)

In [17]:
np.isin([2,5,4,3], arr1)

array([ True,  True, False, False])

In [24]:
np.sort(arr1)

array([ 2,  5,  9, 10, 15, 20])

In [25]:
np.median(arr1)

np.float64(9.5)

In [ ]:
np.percentile(arr1, 25)
np.percentile(arr1, 50)
np.percentile(arr1, 75)
np.percentile(arr1, 100)

np.float64(6.0)

In [41]:
arr1[np.where(arr1<11)]

array([10,  2,  5,  9])