In [1]:
import numpy as np

In [2]:
a1=np.array([10,20,30])
print(a1)

[10 20 30]


In [3]:
np.power(a1,2) #It is used to get the power of each element in array

array([100, 400, 900])

In [4]:
np.sum(a1) # It is going to add all the elements in the array

np.int64(60)

In [5]:
np.std(a1) # It is used to get standard deviation of particular arrray

np.float64(8.16496580927726)

In [6]:
np.mean(a1) # It is used to get mean of that particular array

np.float64(20.0)

In [7]:
np.var(a1) # It is used to get the varience of that particular array. Varience checks how far our value is away from the mean value.

np.float64(66.66666666666667)

In [8]:
a2=np.array([1,0,2]) # It is used to get exponential value for each element in the array
np.exp(a2)

array([2.71828183, 1.        , 7.3890561 ])

In [9]:
a3=np.array([2.71828183, 1.        , 7.3890561 ])
np.log(a3) # It is used to retrieve the value of that power.

array([1., 0., 2.])

In [10]:
a4=np.array([10,2,15,5,9,20])
a4

array([10,  2, 15,  5,  9, 20])

In [11]:
np.isin(20, a4) # It works as membership operator and it is used to check whether that number is in particular array or not
np.isin(2,a4)

array(True)

In [12]:
np.isin([2,5,4,3], a4)

array([ True,  True, False, False])

In [13]:
np.sort(a4) # it is used for sorting

array([ 2,  5,  9, 10, 15, 20])

In [14]:
np.median(a4) # It is used to get median in that array

np.float64(9.5)

In [15]:
np.percentile(a4, 25) # It is used to get percentage of that array and 25 indicates 25%
np.percentile(a4, 50)
np.percentile(a4, 75)
np.percentile(a4, 100)

np.float64(20.0)

In [16]:
a4[np.where(a4<11)] # It is used to check the condition

array([10,  2,  5,  9])

In [17]:
arr1=np.array([10,20,30])
print(arr1)

[10 20 30]


In [ ]:
s_a=np.copy(arr1) # it is used to create the shallow copy of particular array
print(s_a)

s_a[0]=110
print(s_a)
print()
print(arr1)

[10 20 30]
[110  20  30]

[10 20 30]


In [ ]:
arr2=arr1.view() # It is used to copy the array but it stores the elements in same location.
print('arr2:',arr2)
print('arr1:',arr1)
print()

arr2[-1]=200   # The main difference b\w copy and view method is, when we update the array with new elements, the copy() willn't update with original array but when come to view(), it also update with original array
print('arr2:',arr2)
print('arr1:',arr1)

arr2: [10 20 30]
arr1: [10 20 30]

arr2: [ 10  20 200]
arr1: [ 10  20 200]


In [22]:
arr3=np.array([[1,2,3],[10,20,30]])
print(arr3)

[[ 1  2  3]
 [10 20 30]]


In [ ]:
x=arr3.ravel() # It is used to convert any type of array into 1D array like reshape() but when we update the array with new element then it works as view(), it update the value with both original array as well as updated array
print(x)
print()

x[0]=50
print(x)
print()
print(arr3)

[50  2  3 10 20 30]

[50  2  3 10 20 30]

[[50  2  3]
 [10 20 30]]


In [ ]:
arr4=np.array([[11,22,33],[4,67,80]])
print(arr4)
print()

y=arr4.flatten()   # It also works like reshape() method, which converts the any type of array into 1D arrray and it is independent
print(y)
print()

y[-1]=900       # When we update the array with new elements, it doesn't update with original array
print(y)
print(arr4)

[[11 22 33]
 [ 4 67 80]]

[11 22 33  4 67 80]

[ 11  22  33   4  67 900]
[[11 22 33]
 [ 4 67 80]]
